{% set name = "aicspylibczi" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/aicspylibczi-{{ version }}.tar.gz
  sha256: ab525093932cba930593dc2e3f648ff991daae8c91d9edc4f85e2bc7975d2bd3

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.18
    - ninja
  host:
    - python
    - setuptools >=42
    - pytest-runner
    - pip
  run:
    - python
    - numpy >=1.14.1

test:
  imports:
    - aicspylibczi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AllenCellModeling/aicspylibczi
  summary: A python module and a python extension for Zeiss (CZI/ZISRAW) microscopy files.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - multimeric
